services:
  # java:
  #   platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: src/Dockerfile.alpine
  #   env_file:
  #     - ./envs/.env.docker
  #   ports:
  #     - '8080'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
