services:
  # java:
  #   platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: src/Dockerfile.alpine
  #   env_file:
  #     - ./envs/.env.docker
  #   ports:
  #     - '8080'

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - ./envs/containerized/pgadmin.env
    ports:
      - 5001:80
      - 5002:443
    volumes:
      - ./config/postgres/certs/server.cert:/certs/server.cert:ro
      - ./config/postgres/certs/postgres_cert.key:/certs/server.key:ro
    links:
      - "postgres:postgres"
    # networks:
    #   - api
    # networks:
    #   - traefiknet

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
